name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore "./PlcSimAdvancedInterface/ConsoleApp/ConsoleApp.csproj"
    - name: Build
      run: dotnet build "./PlcSimAdvancedInterface/ConsoleApp/ConsoleApp.csproj" --no-restore
    - name: Test
      run: dotnet test "./PlcSimAdvancedInterface/ConsoleApp/ConsoleApp.csproj" --no-build --verbosity normal
    - name: Publish
      run: dotnet publish "./PlcSimAdvancedInterface/ConsoleApp/ConsoleApp.csproj" -c Release -o console-application
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: console-app
        path: "./PlcSimAdvancedInterface/ConsoleApp"
